name: Test cURL Installation

on:
  workflow_dispatch:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Remove Node and Java binaries
        run: |
          # Remove Node binary if present
          NODE=$(which node || true)
          if [ -n "$NODE" ]; then
          echo "Removing Node at $NODE"
          sudo rm -f "$NODE"
          fi
          
          # Remove Java binary if present
          JAVA=$(which java || true)
          if [ -n "$JAVA" ]; then
          echo "Removing Java at $JAVA"
          sudo rm -f "$JAVA"
          fi
          
          # Remove toolcache path fragments from PATH to be sure
          NEW_PATH=$(echo "$PATH" | tr ':' '\n' | grep -v '/opt/hostedtoolcache' | tr '\n' ':' | sed 's/:$//')
          
          echo "PATH=$NEW_PATH" >> $GITHUB_ENV

      - name: Check that Node and Java are not present
        run: |
          echo "PATH is: $PATH"
          
          if which node; then
            echo "ERROR: Node is still present"
            exit 1
          fi
          
          if which java; then
            echo "ERROR: Java is still present"
            exit 1
          fi
          
          echo "OK: Node and Java are not present"

      - uses: browser-actions/setup-chrome@v1
        id: setup-chrome

      - name: Install and test
        run: |
          curl -fsSL https://raw.githubusercontent.com/quarkdown-labs/get-quarkdown/refs/heads/auto-pm/install.sh | sudo env "PATH=$PATH" bash
          
          echo ".docname {test}" > main.qd
          
          echo "Puppeteer executable path:"
          echo "$PUPPETEER_EXECUTABLE_PATH"
          
          quarkdown c main.qd -o ./output
          
          ls ./output
          
          if [ ! -d "./output/test" ]; then
            echo "Output directory not found" >&2
            exit 1
          fi
          
          quarkdown c main.qd -o ./output --pdf --pdf-no-sandbox
          
          ls ./output
          
          if [ ! -f "./output/test.pdf" ]; then
            echo "Output PDF not found" >&2
            exit 1
          fi
        shell: bash
        env:
          PUPPETEER_EXECUTABLE_PATH: ${{ steps.setup-chrome.outputs.chrome-path }}
