name: Test cURL Installation

on:
  workflow_dispatch:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Remove Node and Java from PATH
        id: remove-tools
        run: |
          NEW_PATH=$(echo "$PATH" | tr ':' '\n' | grep -v '/opt/hostedtoolcache' | tr '\n' ':' | sed 's/:$//')
          NEW_PATH=$(echo "$NEW_PATH" | tr ':' '\n' | grep -v '/usr/bin/java' | tr '\n' ':' | sed 's/:$//')
          echo "PATH=$NEW_PATH" >> $GITHUB_ENV
    
      - name: Check missing dependencies
        run: |
          if which node; then
            echo "ERROR: Node is present"
            exit 1
          fi
          if which java; then
            echo "ERROR: Java is present"
            exit 1
          fi
          echo "OK: Neither Node nor Java found"

      - uses: browser-actions/setup-chrome@v1
        id: setup-chrome

      - name: Install and test
        run: |
          curl -fsSL https://raw.githubusercontent.com/quarkdown-labs/get-quarkdown/refs/heads/main/install.sh | sudo env "PATH=$PATH" bash
          
          echo ".docname {test}" > main.qd
          
          echo "Puppeteer executable path:"
          echo "$PUPPETEER_EXECUTABLE_PATH"
          
          quarkdown c main.qd -o ./output
          
          ls ./output
          
          if [ ! -d "./output/test" ]; then
            echo "Output directory not found" >&2
            exit 1
          fi
          
          quarkdown c main.qd -o ./output --pdf --pdf-no-sandbox
          
          ls ./output
          
          if [ ! -f "./output/test.pdf" ]; then
            echo "Output PDF not found" >&2
            exit 1
          fi
        shell: bash
        env:
          PUPPETEER_EXECUTABLE_PATH: ${{ steps.setup-chrome.outputs.chrome-path }}
