name: Test Homebrew Installation

on:
  workflow_dispatch:
  push:

jobs:
  test:
    runs-on: macos-latest

    steps:
      - uses: Homebrew/actions/setup-homebrew@main

      - name: Install and test
        run: |
          brew tap quarkdown-labs/quarkdown
          brew install quarkdown-labs/quarkdown/quarkdown
          
          echo ".docname {test}" > main.qd
          
          echo "Puppeteer executable path:"
          echo "$PUPPETEER_EXECUTABLE_PATH"
          
          quarkdown c main.qd -o ./output
          
          ls ./output
          
          if [ ! -d "./output/test" ]; then
            echo "Output directory not found" >&2
            exit 1
          fi
          
          quarkdown c main.qd -o ./output --pdf --pdf-no-sandbox
          
          ls ./output
          
          if [ ! -f "./output/test.pdf" ]; then
            echo "Output PDF not found" >&2
            exit 1
          fi
        shell: bash