name: Test PowerShell Installation

on:
  workflow_dispatch:
  push:

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Install and test
        run: |
          Invoke-RestMethod -Uri https://raw.githubusercontent.com/quarkdown-labs/get-quarkdown/refs/heads/main/install.ps1 | Invoke-Expression

          $content = ".docname {test}"
          $content | Out-File -FilePath main.qd -Encoding utf8

          quarkdown c main.qd -o ./output

          Get-ChildItem -Path ./output

          if (-Not (Test-Path -Path "./output/test")) {
            Write-Error "Output directory not found"
          }

          quarkdown c main.qd -o ./output --pdf

          Get-ChildItem -Path ./output

          if (-Not (Test-Path -Path "./output/test.pdf")) {
            Write-Error "Output PDF not found"
          }
        shell: powershell
